name: CD_Pipeline

on:
  workflow_run:
    workflows: ["CI_Pipeline"]
    types: 
      - completed

jobs:

  Deploy:

    runs-on: self-hosted

    steps: 
    - name: Pull Docker image
      run: docker pull xgera/babyflask:latest
    - name: Delete Old Docker Container
      run: docker rm -f babyflask || true
    - name: Run Docker Container
      run: docker run -d -p 5000:5000 -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} -e SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} --name babyflask xgera/babyflask:latest